[build]
  publish = "dist/lucy-zion-thatcher/browser"
  command = "npm run build:prod"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://lucy-zion-thatcher-cms.up.railway.app/.*"]
